project_id = "aoszitfxsnwxbocthejl"

[functions.create-lemonsqueezy-checkout]
verify_jwt = false

[functions.lemonsqueezy-webhook]
verify_jwt = false


[functions.approve-order]
verify_jwt = true

[functions.illustrate-hero-photo]
verify_jwt = true

[functions.generate-character-illustration]
verify_jwt = false

[functions.generate-single-page]
verify_jwt = true

[functions.compile-storybook-pdf]
verify_jwt = true

[functions.cleanup-orphaned-storage]
verify_jwt = false