project_id = "aoszitfxsnwxbocthejl"

[functions.create-lemonsqueezy-checkout]
verify_jwt = false

[functions.lemonsqueezy-webhook]
verify_jwt = false

[functions.generate-storybook]
verify_jwt = true

[functions.approve-order]
verify_jwt = true

[functions.illustrate-hero-photo]
verify_jwt = true