import { PageWrapper } from "@/components/layout/PageWrapper";

const Terms = () => {
  return (
    <PageWrapper>
      <div className="container mx-auto max-w-3xl px-4 py-12">
        <h1 className="text-4xl md:text-5xl font-heading font-bold mb-2 text-center">Terms of Service</h1>
        <p className="text-sm text-muted-foreground text-center mb-10">Last updated: May 10, 2026</p>

        <div className="space-y-8 text-foreground/90 leading-relaxed">
          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using ArtBookMagic (the “Service”), you agree to be bound by these Terms of Service.
              If you do not agree, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">2. Eligibility</h2>
            <p>
              You must be at least 18 years old and the parent or legal guardian of the child featured in the storybook
              to use the Service. By placing an order, you represent that you have the right to upload the photo and
              personal details you provide.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">3. The Service</h2>
            <p>
              ArtBookMagic generates a personalized digital storybook (delivered as a PDF) that incorporates the
              child’s name, likeness, and other personalization details you provide. The illustrations are produced
              with the help of artificial intelligence and may vary in style or quality from order to order.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">4. Your Content</h2>
            <p>
              You retain ownership of the photos and personal details you upload (“Your Content”). By submitting Your
              Content, you grant us a limited, non-exclusive, royalty-free license to process, store, and use it for
              the sole purpose of fulfilling your order and providing customer support.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">5. Acceptable Use</h2>
            <p>You agree not to upload any photo or content that:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>contains nudity, sexual content, violence, or otherwise unsafe imagery;</li>
              <li>depicts a person other than your own child without that person’s (or their guardian’s) consent;</li>
              <li>infringes any third party’s intellectual property or privacy rights; or</li>
              <li>violates any applicable law.</li>
            </ul>
            <p className="mt-2">
              We use automated checks to filter out unsafe uploads and may refuse or cancel any order at our discretion.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">6. Intellectual Property</h2>
            <p>
              The story templates, base illustrations, branding, and software are owned by ArtBookMagic. The final
              personalized PDF is licensed to you for personal, non-commercial use only. You may not resell or
              redistribute the storybook.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">7. Payments</h2>
            <p>
              Prices are listed in U.S. dollars and payments are processed through our payment provider (LemonSqueezy).
              All sales are subject to our <a className="text-primary underline" href="/refund">Refund Policy</a>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">8. Disclaimers</h2>
            <p>
              The Service is provided “as is.” Because illustrations are generated by AI, exact resemblance, style, or
              detail cannot be guaranteed. We do not warrant that the Service will be error-free or uninterrupted.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, ArtBookMagic shall not be liable for any indirect, incidental,
              special, or consequential damages. Our total liability for any claim shall not exceed the amount you paid
              for the order giving rise to the claim.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">10. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. The “Last updated” date above will reflect the latest
              revision. Continued use of the Service after changes are posted constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">11. Contact</h2>
            <p>
              Questions about these Terms? Email us at{" "}
              <a className="text-primary underline" href="mailto:support@artbookmagic.com">
                support@artbookmagic.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </PageWrapper>
  );
};

export default Terms;